services:
  makoto:
    build: .
    depends_on:
      - redis
    environment:
      MAKOTO_MODE: sender
      MAKOTO_TIMEZONE: Asia/Jakarta
      MAKOTO_RATE_LIMIT_PER_MINUTE: 100
      REDIS_ADDR: ${REDIS_ADDR:-redis:6379}
      REDIS_PASSWORD: ${REDIS_PASSWORD:-}
      REDIS_DB: ${REDIS_DB:-0}
      MAKOTO_QUEUE_NAME: ${MAKOTO_QUEUE_NAME:-birthday_email_jobs}
      KIRIM_EMAIL_USERNAME: ${KIRIM_EMAIL_USERNAME:-kyouhobbyshopdev}
      KIRIM_EMAIL_API_TOKEN: ${KIRIM_EMAIL_API_TOKEN:-}
      KIRIM_EMAIL_BASE_URL: ${KIRIM_EMAIL_BASE_URL:-https://smtp-app.kirim.email}
      KIRIM_EMAIL_DOMAIN: ${KIRIM_EMAIL_DOMAIN:-kyou.id}
      KIRIM_EMAIL_VALIDATE: ${KIRIM_EMAIL_VALIDATE:-false}
      KIRIM_EMAIL_FROM_EMAIL: ${KIRIM_EMAIL_FROM_EMAIL:-nandayo@kyou.id}
      KIRIM_EMAIL_FROM_NAME: ${KIRIM_EMAIL_FROM_NAME:-Kyou.id}
      MAKOTO_TEMPLATE_IDS: ${MAKOTO_TEMPLATE_IDS:-tpl_001,tpl_002,tpl_003}
      KYOU_ID_API_BASE_URL: ${KYOU_ID_API_BASE_URL:-https://kyou.id}
      KYOU_ID_API_TOKEN: ${KYOU_ID_API_TOKEN:-}
      DISCORD_WEBHOOK_ENABLED: ${DISCORD_WEBHOOK_ENABLED:-true}
      DISCORD_WEBHOOK_URL: ${DISCORD_WEBHOOK_URL:-}

  redis:
    image: redis:7-alpine
